addons:
  sauce_connect: true
language: node_js
node_js:
  - 15

install:
  - # start your web application and listen on `localhost`
  - cd my-app
  - yarn add chromedriver
  - yarn add selenium-side-runner
  - npm install

script:
- npm test
- npm start & selenium-side-runner -c \"goog:chromeOptions.args=[--headless,--nogpu] browserName=chrome\" ./SeleniumTests/GroupA-Frontend.side;