addons:
  chrome: stable
language: node_js
node_js:
  - 13

install:
  - # start your web application and listen on `localhost`
  - cd my-app
  - npm install -g add selenium-side-runner
  - npm install -g chromedriver
  - npm install

script:
- npm test
- npm start & sleep 10 & selenium-side-runner -c "chromeOptions.args=[disable-infobars, headless] browserName=chrome" ./SeleniumTests/GroupA-Frontend.side;