addons:
  sauce_connect: true
language: node_js
node_js:
  - 10

install:
  - # start your web application and listen on `localhost`
  - cd my-app
  - npm install -g add selenium-side-runner
  - npm install -g chromedriver
  - npm install

script:
- npm test
- npm start & selenium-side-runner -c "goog:chromeOptions.args=[disable-infobars, headless] browserName=chrome" ./SeleniumTests/GroupA-Frontend.side;