addons:
  sauce_connect: true
language: node_js
node_js:
  - 15

before_install:
  - # start your web application and listen on `localhost`
  - cd my-app
  - npm install
  - npm install -g chromedriver
  - npm install -g selenium-side-runner
  - selenium-side-runner -c "browserName=chrome" ./SeleniumTests/GroupA-Frontend.side

script:
- npm test
- npm start & selenium-side-runner -c \"goog:chromeOptions.args=[--headless,--nogpu] browserName=chrome\" ./SeleniumTests/GroupA-Frontend.side;